//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrantApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Certificate()
        {
            this.Entrant1 = new HashSet<Entrant>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Entrant { get; set; }
        public string Number { get; set; }
        public int Russian_language { get; set; }
        public int Literature { get; set; }
        public int Native_language { get; set; }
        public int Nativa_literature { get; set; }
        public int Algebra { get; set; }
        public int Geometry { get; set; }
        public int History { get; set; }
        public int Social_studies { get; set; }
        public int Geography { get; set; }
        public int Physics { get; set; }
        public int Biology { get; set; }
        public int Chemistry { get; set; }
        public int Foreign_language { get; set; }
        public int OBZH { get; set; }
        public int Informatics { get; set; }
        public int Physica_culture { get; set; }
        public int Technology { get; set; }
        public int Art { get; set; }
        public int Music { get; set; }
        public Nullable<double> Average { get; set; }
    
        public virtual Entrant Entrant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrant> Entrant1 { get; set; }
    }
}
